{ pkgs, ... }:
{
  home.username = "xavier";
  home.homeDirectory = "/Users/xavier";
  home.stateVersion = "24.11";   # set once, don't bump casually

  # User packages (your CLI tools live here now, not systemPackages)
  home.packages = with pkgs; [
    ripgrep
    yazi
    claude-code
    gh
  ];

  programs.neovim = {
    enable = true;
    withRuby = false;
    withPython3 = false;
    defaultEditor = true;
    viAlias = true;
    vimAlias = true;
    plugins = with pkgs.vimPlugins; [
      (pkgs.vimPlugins.nvim-treesitter.withPlugins (p: [
        p.lua
	p.nix
	p.typescript
	p.tsx
	p.rust
	p.bash
	p.markdown
	p.javascript
      ]))
      {
        plugin = tokyonight-nvim;
        type = "lua";
        config = ''
          require("tokyonight").setup({
            style = "night",   -- "storm" | "night" | "moon" | "day"
          })
          vim.cmd.colorscheme("tokyonight")
        '';
      }
      {
        plugin = telescope-nvim;
        type = "lua";
        config = ''
          local builtin = require("telescope.builtin")
          vim.keymap.set("n", "<leader>sg", builtin.live_grep, { desc = "Grep" })
          vim.keymap.set("n", "<leader>sS", builtin.lsp_dynamic_workspace_symbols, { desc = "Workspace symbols" })
          vim.keymap.set("n", "<leader><leader>", builtin.find_files, { desc = "Find files" })
        '';
      }
      plenary-nvim # dependency of telescope and others
      nvim-web-devicons # File icons
    ];
    initLua = ''
      vim.g.mapleader = " "
      vim.g.maplocalleader = "\\"
      vim.opt.number = true
      vim.opt.relativenumber = true
      vim.opt.termguicolors = true
      '';
  };

  programs.atuin = { enable = true; enableBashIntegration = true; };
  programs.zoxide = { enable = true; enableBashIntegration = true; options = [ "--cmd cd" ]; };
  programs.oh-my-posh = { 
    enable = true;
    enableBashIntegration = true; 
    useTheme = "amro";
    };

  programs.bash = {
    enable = true;
  };

  programs.lazydocker = {
    enable = true;
  };

  programs.lazygit = {
    enable = true;
    enableBashIntegration = true;
  };

  # Ghostty config, generated by Nix → ~/.config/ghostty/config
  home.file.".config/ghostty/config".text = ''
    font-family = JetBrainsMono Nerd Font
    theme = TokyoNight
  '';
}
