{
  config,
  pkgs,
  inputs,
  ...
}:

{
  imports = [
    ./programs/tmux.nix
    ./programs/nvim.nix
    ./programs/karabiner.nix
    ./programs/pi.nix
    ./programs/wtx.nix
    ./programs/pix.nix
  ];

  home.username = "xavier";
  home.homeDirectory = "/Users/xavier";
  home.stateVersion = "24.11"; # set once, don't bump casually

  home.sessionVariables = {
    # Disable pi's context-mode's MCP server idle self-shutdown
    # Causes annoying ui issues
    CONTEXT_MODE_BRIDGE_IDLE_MS = "0";
  };

  # User packages (your CLI tools live here now, not systemPackages)
  home.packages = with pkgs; [
    (import ./packages/anarlog.nix { inherit pkgs; })
    (import ./packages/hypa.nix { inherit pkgs; })
    (import ./packages/loops.nix { inherit pkgs inputs; })
    ripgrep
    yazi
    claude-code
    gh
    colima
    docker # the CLI only — the daemon lives inside colima's VM
    docker-compose # Normal docker doesn't include the code from here
    nodejs_22
    redis # redis-server + redis-cli
    ngrok
    pnpm
    caddy
    infisical
    worktrunk
  ];

  # Global agent instructions.
  home.file.".claude/CLAUDE.md".source = inputs.agents + "/AGENTS.md";
  home.file.".codex/AGENTS.md".source = inputs.agents + "/AGENTS.md";
  home.file.".config/opencode/AGENTS.md".source = inputs.agents + "/AGENTS.md";
  home.file.".pi/agent/AGENTS.md".source = inputs.agents + "/AGENTS.md";

  # Merge skills from all sources into a single directory.
  home.file.".pi/agent/skills".source = pkgs.symlinkJoin {
    name = "merged-skills";
    paths = [
      (inputs.agents + "/skills")
      (inputs.loops + "/skills")
    ];
  };
  home.file.".claude/skills".source = pkgs.symlinkJoin {
    name = "merged-skills-claude";
    paths = [
      (inputs.agents + "/skills")
      (inputs.loops + "/skills")
    ];
  };

  programs.atuin = {
    enable = true;
    enableBashIntegration = true;
  };
  programs.zoxide = {
    enable = true;
    enableBashIntegration = true;
    options = [ "--cmd cd" ];
  };
  programs.oh-my-posh = {
    enable = true;
    enableBashIntegration = true;
    useTheme = "amro";
  };

  programs.bash = {
    enable = true;
    initExtra = ''
      mkcdir() { mkdir -p "$1" && cd "$1"; }
      ssh-add -l &>/dev/null || ssh-add -t 86400 ~/.ssh/id_ed25519
    '';
  };

  programs.lazydocker = {
    enable = true;
  };

  programs.lazygit = {
    enable = true;
    enableBashIntegration = true;
  };

  programs.ssh = {
    enable = true;
    enableDefaultConfig = false;
    settings."*" = {
      identityFile = "~/.ssh/id_ed25519";
      AddKeysToAgent = "yes";
    };
  };

  programs.git = {
    enable = true;
    settings = {
      user = {
        name = "Xavier Andueza";
        email = "xavier@lyratechnologies.com.au";
      };
      gpg.ssh.allowedSignersFile = "${config.home.homeDirectory}/.ssh/allowed_signers";
    };
    signing = {
      format = "ssh";
      key = "~/.ssh/id_ed25519.pub";
      signByDefault = true;
    };
  };

  # Local trust list for verifying SSH-signed commits (git log --show-signature).
  home.file.".ssh/allowed_signers".text = ''
    xavier@lyratechnologies.com.au ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPbemigCfIIpc0dhm1lwZDtQdwFN64GN4x+U1yK9bS1E xavier@lyratechnologies.com.au
  '';

  programs.bottom = {
    enable = true;
  };

  # Make `docker compose` (the plugin subcommand) resolve to `docker-compose`
  home.file.".docker/cli-plugins/docker-compose".source = "${pkgs.docker-compose}/bin/docker-compose";

  # Ghostty config, generated by Nix → ~/.config/ghostty/config
  home.file.".config/ghostty/config".text = ''
    font-family = JetBrainsMono Nerd Font
    theme = TokyoNight
  '';
}
